name: Docker CI/CD

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # 1. Code clone
      - name: Clone repository
        uses: actions/checkout@v4

      # 2. Build Docker image
      - name: Build Docker image
        run: docker build -t django-backend:v1 .

      # 3. Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Tag image
      - name: Tag Docker image
        run: docker tag django-backend:v1 ${{ secrets.DOCKER_USER }}/django-backend:v1

      # 5. Push image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/django-backend:v1

      # 6. Deploy (run container)
      - name: Deploy container
        run: docker run -d -p 8000:8000 django-backend:v1
